apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  name: fh-swifty-mcp-server
  namespace: fh-swifty-chatbot
spec:
  rules:
  - host: mcp-server.fh-swf.cloud
    http:
      paths:
      - backend:
          service:
            name: fh-swifty-mcp-server
            port:
              number: 80
        path: /
        pathType: Prefix
