apiVersion: v1
kind: Service
metadata:
  name: fh-swifty-mcp-server
  namespace: fh-swifty-chatbot
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8081
  selector:
    io.kompose.service: fh-swifty-mcp-server
status:
  loadBalancer: {}
