apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: fh-swifty-mcp-server
  name: fh-swifty-mcp-server
  namespace: fh-swifty-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fh-swifty-mcp-server
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: fh-swifty-mcp-server
    spec:
      containers:
        - image: fh-swifty-mcp-server
          name: fh-swifty-mcp-server
          ports:
            - containerPort: 8081
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: openai-api-key
            - name: NEO4J_URI
              valueFrom:
                secretKeyRef:
                  name: fh-swifty-chatbot-secrets
                  key: NEO4J_URI
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fh-swifty-chatbot-secrets
                  key: NEO4J_PASSWORD
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 250m
      restartPolicy: Always
      autoMountServiceAccountToken: false
status: {}
