apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: neo4j
  name: neo4j
  namespace: fh-swifty-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - image: neo4j:5.15-community
          name: neo4j
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/password123"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
            requests:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data
        - name: neo4j-logs
          emptyDir: {}
      restartPolicy: Always
status: {}
