apiVersion: v1
kind: Secret
metadata:
  name: fh-swifty-chatbot-secrets
  namespace: fh-swifty-chatbot
type: Opaque
data:
  TAVILY_API_KEY: "dHZseS1kZXYtMllNbGRQSnlMbmJPZUx0Q0FlNU9PRTQ5ZzQ3eUd2RDY="
  LANGSMITH_API_KEY: "bHN2Ml9wdF80Mzc3MTA5MjY3N2Y0Nzk0YjMxYTdmNTM3NThjMjFhNl9kMzQwNzBmZGNj"
  NEO4J_URI: "bmVvNGo6Ly80Ni4yNTIuMTkzLjY0Ojc2ODc="
  NEO4J_PASSWORD: "cC03QW9Tb3V6T2F0UWRaTjYzMy1ZMFJpOGtkWEhleTd2azNXbGhVUWJIbw=="
